class Configs:
    LARGURA_TELA = 1080
    ALTURA_TELA = 720
    VELOCIDADE_PERSONAGEM = 0.2
    LARGURA_PERSONAGEM = 0.2 * LARGURA_TELA
    ALTURA_PERSONAGEM = 0.2 * ALTURA_TELA
    COR_PERSONAGEM = (0, 0, 0)
    COR_FUNDO = (71, 175, 191)